#!/bin/bash

echo "get data"
pid=$(pgrep "mpd")
ids=($(ps --no-headers -ww -p $pid -L -olwp | sed 's/$/ /' | tr  -d '\n'))

echo "set priorities"
# Samba on 1st core
chrt -r -p 49 $(pgrep cifsd)
# Ethernet on 1st core
chrt -r -p 52 $(pgrep irq/150)

# MPD priorities are set in mpd.conf
# Update thread on 1st core

# Decoder and player on 2nd & 3rd core
taskset -pc 1,2 ${ids[2]}
taskset -pc 1,2 ${ids[3]}

# Output thread on 2nd & 3rd core
taskset -pc 1,2 ${ids[4]}
# Main thread on 2,3rd core
taskset -pc 1,2 ${ids[0]}

# Output IRQ on 4rd core
for PID in $(pgrep ci_hdrc) ; do taskset -pc 3 $PID ; done
echo 8 > /proc/irq/72/smp_affinity
echo 8 > /proc/irq/75/smp_affinity
chrt -f -p 99 $(pgrep irq/72)
chrt -f -p 99 $(pgrep irq/75)

# Other tunups
echo noop > /sys/block/mmcblk0/queue/scheduler
echo 0 > /proc/sys/vm/swappiness
renice -n -15 -g $(pidof mpd)

echo 625000 > /proc/sys/kernel/sched_latency_ns
echo 104165 > /proc/sys/kernel/sched_min_granularity_ns
echo 156250 > /proc/sys/kernel/sched_wakeup_granularity_ns
echo 156248 > /proc/sys/kernel/sched_rt_period_us
echo 148436 > /proc/sys/kernel/sched_rt_runtime_us

ifconfig eth0 txqueuelen 10000
ifconfig eth0 mtu 1500
service udev stop
service dbus stop
pkill dhclient
